### ISSUE TITLE
Cijfers verplichten in huisnummer

### ISSUE THREAD

**Issue by Antonvink** [GeenPeil/teken#10]
Je kunt op dit moment bij huisnummer alleen letters invullen, ik zou niet weten waar dit voorkomt in de Nederlande, misschien ook captcha aanpassen zodat eerst cijfers en dan letters verplicht zijn.

Echter goede regex is hiervoor niet mogelijk, dus misschien huisnummer/toevoegsel scheiden. Huisnummer numeriek en toevoegsel alphanumeriek.

(TIP: Misschien postcode database erachter hangen om check te doen op postcode huisnummer, en indien mogelijk plaats vast in te vullen)

**Comment by frenck** [comment]
Opzich kan dit prima, door de regex aan te passen dat het huisnummer in ieder geval begint met een cijfer

**Comment by Antonvink** [comment]
Lijkt me opgelost, voor de volledigheid een huisnummer begint nooit met een 0.

^[0-9][0-9a-zA-Z -]+$
vs.
^[1-9][0-9a-zA-Z -]+$

**Comment by frenck** [comment]
Goede opmerking, toegevoegd :+1:

**Comment by Antonvink** [comment]
Lijkt me opgelost!
