### ISSUE TITLE
Pechtold API uitbreiden call voor het opvragen van statistieken

### ISSUE THREAD

**Issue by frenck** [GeenPeil/teken#11]
Het zou mooi zijn om her en der een counter te kunnen plaatsen over waar we staan, deze data is immers gewoon beschikbaar in de database.

Kunnen we Pechtold niet uitbreiden met een call hiervoor?

**Comment by Antonvink** [comment]
Misschien leuker om dit op de bedankt pagina of in de mail te zetten, dit is gelijk een incentive om te tekenen.

(U bent nummer: 12392)

**Comment by GeertJohan** [comment]
Er komt een API, maar die word afgesloten met een passphrase en daar gaan de ontwikkelaars van GeenStijl tegenaan praten om een mooie counter te tonen.

**Comment by frenck** [comment]
Check... Dan kan deze dicht :+1:
