### ISSUE TITLE
Handtekeningveld "start niet"

### ISSUE THREAD

**Issue by MichielVdAnker** [GeenPeil/teken#15]
Er zijn berichten van mensen dat het handtekeningveld niet start na er op te drukken.

Het zijn er te veel om ze allemaal te wijten aan iOS click-drag achtige issues.

**Comment by Antonvink** [comment]
Is vaker een probleem geweest met ember op iOs touch enabled devices. Zeker in combinatie met non clickable elements. 

Echter bij al deze mensen werkt de volgende button wel (gezien het feit dat ze bij de laatste stap zijn). Ik denk dat er in plaats van een <div> er een <a> of <button> van maken dus ook het probleem zou moeten oplossen

**Comment by MichielVdAnker** [comment]
Jup, ja er begint me weer iets te dagen. iOS handelt in geval van non
clickable elementen click events wel af als het element CSS
"cursor:pointer;" heeft. Te fragiel dus in combinatie met Ember.

Ik maak er vanavond wel gewoon een button van.

2015-08-20 14:55 GMT+02:00 Antonvink notifications@github.com:

**Comment by MichielVdAnker** [comment]
Nieuwe flow en tekst

![handtekening_nieuw](https://cloud.githubusercontent.com/assets/718900/9414137/7113e954-4836-11e5-9c16-5dcaf5437033.png)

![handtekening_gezet](https://cloud.githubusercontent.com/assets/718900/9414138/78374a78-4836-11e5-8436-d13caf3ce86b.png)
