### ISSUE TITLE
Verduidelijken dat alleen eerste officieele naam ingevoerd moet worden

### ISSUE THREAD

**Issue by GeertJohan** [GeenPeil/teken#3]
Hoe? Dikgedrukt? `alert()` op stap1?

**Comment by StephanBijzitter** [comment]
Plaatje natuurlijk, duidelijker kan niet. Alerts worden vaak weg-geklikt zonder gelezen te worden.

**Comment by MichielVdAnker** [comment]
Ik zet een subtext in met de strekking: "Let op: gebruik de naam die hoort bij de eerste letter van uw initialen.¨

**Comment by frenck** [comment]
Ja of misschien:

"In het geval u meerdere voornamen heeft (Bijvoorbeeld Henk Jan Diederik), dan vult u alleen Henk in"

Een voorbeeld doet wonderen?

En we moeten natuurlijk ook niet hebben dat mensen hun Roepnaam gaan invullen

**Comment by GeertJohan** [comment]
De subtext is iig doorgevoerd.

**Comment by JanJaapE** [comment]
Het is inderdaad enigszins onduidelijk. Officiele naam is Jan Jacob. Moet het dan Janjacob worden of Jan?

Misschien goed om paar voorbeelden te geven of dit in de FAQ op te nemen. Ik vermoed dat dit voor meer mensen een probleem gaat zijn.

**Comment by MichielVdAnker** [comment]
Hoi Jan (Jacob),

Wat staat er in je paspoort?

Mijn voornamen zijn Michiel Justin. Op mijn rijbewijs staat Michiel J.

Ik las ergens dat je eerste officiële voornaam in je paspoort vetgedrukt
is. Maar heb 'm niet bij de hand.

Ik zou echter Jan-Jacob in plaats van Janjacob invullen.

**Comment by JanJaapE** [comment]
Paspoort staat Jan Jacob

Rijbewijs Jan J (Dat wist ik niet eens). 

Dan vul ik hem nog maar een keer denk ik? Ik had nu maar Janjacob ingevuld...

**Comment by MichielVdAnker** [comment]
De app is aangepast om duidelijk te maken dat mensen hun paspoort c.q. identiteitskaart moeten gebruiken. Extra uitleg hier: http://geenpeil.nl/digitaal-tekenen/
