### ISSUE TITLE
Letters buiten a-z toestaan in namen.

### ISSUE THREAD

**Issue by GeertJohan** [GeenPeil/teken#5]
https://twitter.com/burningbjorn/status/634080215606652928

**Comment by StephanBijzitter** [comment]
Sta direct alles toe. Mensen die wel stemrecht hebben, maar namen uit een ander alfabet hebben, kunnen op die manier ook tekenen.

Gewoon niet limiteren, alleen zorgen dat er geen code in kan staan.

**Comment by GeertJohan** [comment]
Fixed in c172822aec194ab1f066633d9255a506946a0f36

**Comment by StephanBijzitter** [comment]
Maar wat als mijn naam `Стефан` is? Met de huidige regex sluit je nog steeds heel veel mensen met stemrecht buiten.
