### ISSUE TITLE
25 karakters voor straatnamen is te kort

### ISSUE THREAD

**Issue by yorickpeterse** [GeenPeil/teken#9]
De limiet van 25 karakters voor een straatnaam is wel erg krap. Dit zorgt er voor dat namen zoals "Eerste Jan van der Heijdenstraat" niet geaccepteerd worden.

**Comment by frenck** [comment]
Op het formulier dat naar de kiesraad moet, zijn maar 25 karakter posities voor de straatnaam. Dit is geen beperking van de app, maar een beperking van het formulier dat naar de kiesraad moet.

Voor dergelijke straatnamen zul je dus Jvd Heijdenstraat moeten gebruiken oid.

**Comment by yorickpeterse** [comment]
Ah, lekker handig is dat. In dat geval valt er helaas weinig aan te doen :/

**Comment by frenck** [comment]
@GeertJohan  Volgens mij kan deze dicht...
